Update CHANGELOG.md
hashicorp/terraform-provider-google-beta pull request #3048
Opened 2021-03-11 21:40 UTC by melinath

2021-03-11 22:09 UTC, melinath commented
attn @c2thorn re: the revert here since the fix _should_ be in next release. Tracking ticket is here: https://github.com/hashicorp/terraform-provider-google/issues/8667

2021-03-12 17:08 UTC, c2thorn requested changes

2021-03-12 17:08 UTC, c2thorn commented on CHANGELOG.md
> +* container: fixed container cluster not removed from the state when received 404 error on delete call for the resource `google_container_cluster` ([#3018](https://github.com/hashicorp/terraform-prov
I believe these are considered bug fixes (their tracking issue was a bug)

2021-03-12 17:08 UTC, c2thorn commented on CHANGELOG.md
> +* datafusion : new instance type added for the resource `google_data_fusion_instance` ([#3015](https://github.com/hashicorp/terraform-provider-google-beta/pull/3015))
```suggestion
* datafusion : added support for the `DEVELOPER` instance type to `google_data_fusion_instance` ([#3015](https://github.com/hashicorp/terraform-provider-google-beta/pull/3015))
```

2021-03-12 17:37 UTC, melinath commented
@c2thorn thanks! Fixed.

2021-03-12 17:59 UTC, c2thorn approved these changes

2021-03-15 15:16 UTC, merged