Added datas source google kms secret asymmetric
hashicorp/terraform-provider-google-beta pull request #3052
Opened 2021-03-13 13:10 UTC by mvanholsteijn

This PR add the data source `google_kms_secret_asymmetric`. I chose to put `_asymmetric` as a suffix to ensure that in the documentation it will appear next to `google_kms_secret`.

This partly deals with issue #6462

2021-03-13 18:56 UTC, dennisvink approved these changes

2021-03-16 09:46 UTC, mvanholsteijn commented
Hi @melinathI am looking forward to your review!  Just let me know if you have any questions for me, or whether I have to change things here.

2021-03-16 18:58 UTC, melinath requested changes
Hello, thanks for your PR! This API looks like a GA api; I'll need to upstream your changes to https://github.com/GoogleCloudPlatform/magic-modules, after which they'll be put into both the beta and GA providers. Does that seem correct?

This implementation seems fine; I just have a couple questions.

2021-03-16 18:58 UTC, melinath commented on website/docs/d/kms_secret_asymmetric.html.markdown
> +  `projects/{project}/locations/{location}/keyRings/{keyring}}/cryptoKeys/{key}}/cryptoKeyVersions/{version}`.
typo: a couple extra closing curly braces

2021-03-17 07:53 UTC, mvanholsteijn commented on google-beta/config.go
> +	clientKms, err := kms.NewKeyManagementClient(ctx, option.WithUserAgent(userAgent), option.WithEndpoint(endpoint))
I am using the library specified by the [documentation to use](https://cloud.google.com/kms/docs/reference/libraries#client-libraries-install-go). The package documentation of [google.golang.org/api/cloudkms/v1 ](https://pkg.go.dev/google.golang.org/api@v0.42.0/cloudkms/v1#section-documentation) also states that the  package is deprecated.

2021-03-17 07:57 UTC, mvanholsteijn commented on google-beta/data_source_google_kms_secret_asymmetric.go
> +func validateBase64WithWhitespaces(i interface{}, val string) ([]string, []error) {
The validateBase64String does not allow for whitespace in the base64 encoding. As the cyphertext is quite long, I wanted to be able to specify the output of openssl base64 which does include whitespace.

2021-03-17 08:00 UTC, mvanholsteijn commented on website/docs/d/kms_secret_asymmetric.html.markdown
> +  `projects/{project}/locations/{location}/keyRings/{keyring}}/cryptoKeys/{key}}/cryptoKeyVersions/{version}`.
fixed

2021-03-19 17:36 UTC, melinath approved these changes
LGTM - I'll get to work upstreaming.

2021-03-19 18:49 UTC, mvanholsteijn commented
@melinath great! Thank you!

2021-03-25 22:34 UTC, merged