Update CHANGELOG.md
hashicorp/terraform-provider-google-beta pull request #4381
Opened 2022-06-10 17:44 UTC by shuyama1

2022-06-10 17:50 UTC, slevenick requested changes

2022-06-10 17:50 UTC, slevenick commented on CHANGELOG.md
> +* composer: promoted `config.master_authorized_networks_config` in `google_composer_environment` resource to GA. ([#4355](https://github.com/hashicorp/terraform-provider-google-beta/pull/4355))
Remove as it is related to GA only

2022-06-10 17:50 UTC, slevenick commented on CHANGELOG.md
> +* cloudfunctions2: Made `google_cloudfunctions2_function.event_trigger.service_account_email` and `google_cloudfunctions2_function.service_config.service_account_email` configurable. (beta) ([#4367](
Remove (beta), maybe reword this?

2022-06-10 17:50 UTC, slevenick commented on CHANGELOG.md
> +* container: add `managed_prometheus` to `monitoring_config` in `google_container_cluster` (beta) ([#4373](https://github.com/hashicorp/terraform-provider-google-beta/pull/4373))
added

2022-06-10 23:32 UTC, shuyama1 commented on CHANGELOG.md
> +* composer: promoted `config.master_authorized_networks_config` in `google_composer_environment` resource to GA. ([#4355](https://github.com/hashicorp/terraform-provider-google-beta/pull/4355))
removed!

2022-06-10 23:33 UTC, shuyama1 commented on CHANGELOG.md
> +* cloudfunctions2: Made `google_cloudfunctions2_function.event_trigger.service_account_email` and `google_cloudfunctions2_function.service_config.service_account_email` configurable. (beta) ([#4367](
Done! Thanks!

2022-06-10 23:33 UTC, shuyama1 commented on CHANGELOG.md
> +* container: add `managed_prometheus` to `monitoring_config` in `google_container_cluster` (beta) ([#4373](https://github.com/hashicorp/terraform-provider-google-beta/pull/4373))
Done.

2022-06-13 15:52 UTC, slevenick approved these changes

2022-06-14 19:33 UTC, merged