beta - 4.67.0 - release notes
hashicorp/terraform-provider-google-beta pull request #5679
Opened 2023-05-24 21:58 UTC by ScottSuarez

2023-05-25 22:41 UTC, melinath requested changes
it looks like all the links are for the GA provider rather than beta - is there any chance that this was generated from the GA provider? If so it might be good to re-generate from the beta provider to make sure nothing is missed. Other comments left inline :-)

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* **New Data Source:** `google_**_iam_policy` ([#14662](https://github.com/hashicorp/terraform-provider-google/pull/14662))
```suggestion
* **New Data Source:** `google_*_iam_policy` ([#14662](https://github.com/hashicorp/terraform-provider-google/pull/14662))
```

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* **New Data Source:** google_vertex_ai_index ([#14640](https://github.com/hashicorp/terraform-provider-google/pull/14640))
```suggestion
* **New Data Source:** `google_vertex_ai_index` ([#14640](https://github.com/hashicorp/terraform-provider-google/pull/14640))
```

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* cloudrun: Added beta field `template.spec.columes.empty_dir` to `google_cloud_run_service` ([#14647](https://github.com/hashicorp/terraform-provider-google/pull/14647))
```suggestion
* cloudrun: Added field `template.spec.volumes.empty_dir` to `google_cloud_run_service` ([#14647](https://github.com/hashicorp/terraform-provider-google/pull/14647))
```

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* cloudrun: Added field `template.spec.containers.name` to `google_cloud_run_service` ([#14647](https://github.com/hashicorp/terraform-provider-google/pull/14647))
it looks like all of the links are to tpg instead of tpg-beta

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* compute: - promoted field `network_performance_config` to ga ([#14678](https://github.com/hashicorp/terraform-provider-google/pull/14678))
Note that in GA this should probably be rewritten to say something like "added field X to Y"

```suggestion
```

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* firebase: added additional import formats for app resources, removed the need to supply duplicate projects in some cases ([#14638](https://github.com/hashicorp/terraform-provider-google/pull/14638)
this should possibly be rewritten to emphasize user impact / not use as much technical language

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* privateca: added support for encoding_format on CaPool ([#14663](https://github.com/hashicorp/terraform-provider-google/pull/14663))
```suggestion
* privateca: added support for `encoding_format` on `google_privateca_ca_pool` ([#14663](https://github.com/hashicorp/terraform-provider-google/pull/14663))
```

2023-05-25 22:41 UTC, melinath commented on CHANGELOG.md
> +* provider: fixed an issue where mtls transports were not used consistently ([#14621](https://github.com/hashicorp/terraform-provider-google/pull/14621))
should probably be rewritten to emphasize user impact

2023-05-30 17:21 UTC, roaks3 approved these changes

2023-05-30 18:04 UTC, merged