5.4.0 changelog
hashicorp/terraform-provider-google-beta pull request #6571
Opened 2023-10-25 20:34 UTC by slevenick

2023-10-25 20:39 UTC, shuyama1 commented on CHANGELOG.md
> +* sql: added `ssl_mode` field to `google_sql_database_instance` resource ([#6564](https://github.com/hashicorp/terraform-provider-google-beta/pull/6564))
```suggestion
```
since this change is reverted

2023-10-25 20:44 UTC, trodge commented on CHANGELOG.md
> +* tpuv2: added`accelerator_config` field to `google_tpu_v2_vm` resource ([#6559](https://github.com/hashicorp/terraform-provider-google-beta/pull/6559))
```suggestion
* tpuv2: added `accelerator_config` field to `google_tpu_v2_vm` resource ([#6559](https://github.com/hashicorp/terraform-provider-google-beta/pull/6559))
```

2023-10-25 20:52 UTC, melinath requested changes

2023-10-25 20:52 UTC, melinath commented on CHANGELOG.md
> +NOTES:
```suggestion
DEPRECATIONS:
* bigquery: deprecated `cloud_spanner.use_serverless_analytics` on `google_bigquery_connection`. Use `cloud_spanner.use_data_boost` instead. ([#6539](https://github.com/hashicorp/terraform-provider-google-beta/pull/6539))

NOTES:
```

2023-10-25 20:52 UTC, melinath commented on CHANGELOG.md
> +* bigquery: added data boost and parallelism input options to `google_bigquery_connection` ([#6539](https://github.com/hashicorp/terraform-provider-google-beta/pull/6539))
```suggestion
* bigquery: added `cloud_spanner.database_role`, `cloud_spanner.use_data_boost`, and `cloud_spanner.max_parallelism` fields to `google_bigquery_connection` ([#6539](https://github.com/hashicorp/terraform-provider-google-beta/pull/6539))
```

2023-10-25 20:52 UTC, melinath commented on CHANGELOG.md
> +* redis: allow `replica_count` to be set to zero in the `google_redis_cluster` resource ([#6534](https://github.com/hashicorp/terraform-provider-google-beta/pull/6534))
This should be a bug rather than an enhancement.

2023-10-25 20:52 UTC, melinath commented on CHANGELOG.md
> +* tpuv2: added more fields to `google_tpu_v2_vm` resource, including `network_config`, `scheduling_config`, `shielded_instance_config`, `service_account` and `data_disks` ([#6555](https://github.com/
could we maybe list all of the added fields instead of just a few of them?

2023-10-25 20:52 UTC, melinath commented on CHANGELOG.md
> +* cloudrunv2: set field `annotations` having all of annotations present on the resource in GCP in data source `google_cloud_run_v2_job` ([#6532](https://github.com/hashicorp/terraform-provider-google
Same change below.

```suggestion
* cloudrunv2: made `annotations` field on the `google_cloud_run_v2_job` data source include all annotations present on the resource in GCP ([#6532](https://github.com/hashicorp/terraform-provider-google-beta/pull/6532))
```

2023-10-27 18:29 UTC, melinath approved these changes

2023-10-27 18:29 UTC, melinath commented on CHANGELOG.md
> +* accesscontextmanager: added support for Access Context Manager's VPC Sub-segmentation feature ([#6553](https://github.com/hashicorp/terraform-provider-google-beta/pull/6553))
I think it might make sense to specify the fields that were added rather than the feature?

2023-10-27 18:29 UTC, melinath commented on CHANGELOG.md
> +* apigee: added support for type in `google_apigee_environment` ([#6562](https://github.com/hashicorp/terraform-provider-google-beta/pull/6562))
```suggestion
* apigee: added support for `type` in `google_apigee_environment` ([#6562](https://github.com/hashicorp/terraform-provider-google-beta/pull/6562))
```

2023-10-30 16:59 UTC, merged